#ifndef _HACKHOURQT_ICONS_H_
#define _HACKHOURQT_ICONS_H_

#define _HACKHOURQT_ICONS_MENU_ 0xE5D2
#define _HACKHOURQT_ICONS_QUIT_ 0xE879
#define _HACKHOURQT_ICONS_CONFIG_ 0XE8B8

#endif // !_HACKHOURQT_ICONS_H_